apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: malware
spec:
  containers:
  - name: HavocC2
    image: piedacoulisse10/havoc:latest # Replace with your image name and tag
    ports:
    - containerPort: 8443
    - containerPort: 40056
---
apiVersion: v1
kind: Service
metadata:
  namespace: malware
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
    nodePort: 31443 # Optional: Specify the NodePort manually
  - protocol: TCP
    port: 40056
    targetPort: 40056
    nodePort: 32080 # Optional: Specify the NodePort manually
  type: NodePort
